### ISSUE TITLE
PORT not recognized as a command 

### ISSUE THREAD

**Issue by giammarcotassinari** [vectara/vectara-answer#136]
Hello,
when doing "npm run start" on windows 10 it crashes, saying something like these

> PORT=4444 react-scripts start

"PORT" not recognized as a command

Am I missing some dependencies?

**Comment by ofermend** [comment]
Hey @giammarcotassinari - thanks for reporting this.
I have created a PR (https://github.com/vectara/vectara-answer/pull/137) that uses cross-env to should address this issue - can you please try that and let me know if it solves the issue for you? Once confirmed it solves it I can merge this branch.

**Comment by ofermend** [comment]
@giammarcotassinari - can you please let me know if this PR (already merged) solves the issue?

**Comment by ofermend** [comment]
closing as resolved.
