### ISSUE TITLE
Docker script output should provide helpful instructions

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-answer#2]
When I run `docker/run.sh`, I get the following output in the terminal:

![image](https://github.com/vectara/vectara-answer/assets/1238659/bcef5432-0da4-45f1-ba71-29da4d15bfe3)

We can make this output more helpful if it concluded with a status message and instructions on how to view the app, shut down the Docker container, and iterate on the application. For example:

```sh
Success! Application is running at http://localhost:80.

🔧 To iterate on this application, make changes to the config and rerun the command you just executed. If you make changes to src/ code, you need to run `npm run build` first. Changes will appear in your browser.

🛑 To shut down the process, open the Docker application and stop the container called vanswer.
```

**Comment by ofermend** [comment]
Solved with https://github.com/vectara/vectara-answer/pull/5
