### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c pip3 install --upgrade awscli" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by sunddytwo** [vectara/vectara-answer#24]
ERROR: failed to solve: process "/bin/sh -c pip3 install --upgrade awscli" did not complete successfully: exit code: 1

**Comment by ofermend** [comment]
New version 1.1 removes the need for AWSCLI altogether. Please try V1.1 and let me know if any issues remain.
