### ISSUE TITLE
Cannot Load Vectara-answer or vectara-ingest

### ISSUE THREAD

**Issue by brianjking** [vectara/vectara-answer#63]
**Describe the bug**

I cannot seem to get the vectara-answer service to run on my local machine or identify how to run it on Fly.io or another external webhost. 

**To Reproduce**
1. Clone https://github.com/vectara/vectara-answer
2. Run `npm install && npm run build` (this builds fine)
3. Setup my `secrets.toml` file with my API key using [default]
4. Setup a `/config/brian/config.yaml`
5. Run `bash docker/run.sh config/brian default`
6. Receive errors

**Expected behavior**

* The app runs at localhost:80 and is accessible and I can use it.

**Screenshots**

**Desktop (please complete the following information):**
Do NOT include your API key.
 - Device: M1 Pro MacBook Pro
 - OS: 13.5.2
 - Browser Chrome 
 - Version Version 117.0.5938.62 (Official Build) (arm64)
 - Corpus ID `1` and Customer ID `3056969352`

**Additional context**

bash docker/run.sh config/brian default                                     (anaconda3)   17:20   17.09.23 

> vectara-answer@1.5.0 build
> react-scripts build

up to date, audited 1421 packages in 1s

245 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 moderate, 8 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Creating an optimized production build...
Compiled with warnings.

[eslint]
src/views/search/controls/OptionsDrawer.tsx
  Line 71:25:  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  126.8 kB  build/static/js/main.70fe9410.js
  7.64 kB   build/static/css/main.b65fd42c.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

[+] Building 1.4s (14/14) FINISHED                                                                                                                      docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 361B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                                              1.2s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                             0.0s
 => [internal] load build context                                                                                                                                       0.1s
 => => transferring context: 3.60MB                                                                                                                                     0.1s
 => [1/8] FROM docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                        0.0s
 => => resolve docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                        0.0s
 => CACHED [2/8] COPY docker/package.json ./                                                                                                                            0.0s
 => CACHED [3/8] RUN npm install                                                                                                                                        0.0s
 => CACHED [4/8] WORKDIR /usr/src/app                                                                                                                                   0.0s
 => CACHED [5/8] COPY public ./public                                                                                                                                   0.0s
 => CACHED [6/8] COPY img ./img                                                                                                                                         0.0s
 => CACHED [7/8] COPY build ./build                                                                                                                                     0.0s
 => CACHED [8/8] COPY docker/server ./server                                                                                                                            0.0s
 => exporting to image                                                                                                                                                  0.1s
 => => exporting layers                                                                                                                                                 0.0s
 => => exporting manifest sha256:6afa66e99fff95d23ef02effe6a5cd7010d728ac8257d0c3e179e6874c01bb3a                                                                       0.0s
 => => exporting config sha256:0df7352ea917f8bf4a82a369613a89b2a2621a0168ff4e06b63bcaf465ca42f3                                                                         0.0s
 => => exporting attestation manifest sha256:40a9006f326a017c1aa4ef03e9be540f6facd66b2c64675ec7dc2ff3f6897550                                                           0.0s
 => => exporting manifest list sha256:f61bbee48ce6a72f4b9cf389a639aca446618c6bb63c53769085d604a3854384                                                                  0.0s
 => => naming to docker.io/library/vectara-answer:latest                                                                                                                0.0s
 => => unpacking to docker.io/library/vectara-answer:latest                                                                                                             0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Unable to find image 'vectara-answer:latest' locally
docker: Error response from daemon: failed to resolve reference "docker.io/library/vectara-answer:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed.
See 'docker run --help'.
Success! Application is running at http://localhost:80.\nTo shut it down use: docker container stop vanswer.

**Comment by cjcenizal** [comment]
Thanks for reporting this @brianjking! I'll look into this and get this fixed.

**Comment by brianjking** [comment]
@cjcenizal Any idea what is wrong? I can't load vectara-ingest either.

I really need to get this running either locally or on AWS/GCP/Azure.

CC: @ofermend

**Comment by brianjking** [comment]
I'm now seeing this @cjcenizal 

bash docker/run.sh config/ask-news default                          (anaconda3)   19:05   17.09.23 

> vectara-answer@1.5.0 build
> react-scripts build


up to date, audited 1432 packages in 1s

246 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 moderate, 8 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Creating an optimized production build...
Compiled with warnings.

[eslint]
src/views/search/controls/OptionsDrawer.tsx
  Line 71:25:  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  126.8 kB  build/static/js/main.70fe9410.js
  7.64 kB   build/static/css/main.b65fd42c.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

[+] Building 0.7s (11/12)                                                                                                                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 361B                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 2.91kB                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                                              0.6s
 => [1/8] FROM docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                        0.0s
 => => resolve docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                        0.0s
 => [internal] load build context                                                                                                                                       0.0s
 => => transferring context: 1.30kB                                                                                                                                     0.0s
 => CACHED [2/8] COPY docker/package.json ./                                                                                                                            0.0s
 => CACHED [3/8] RUN npm install                                                                                                                                        0.0s
 => CACHED [4/8] WORKDIR /usr/src/app                                                                                                                                   0.0s
 => CACHED [5/8] COPY public ./public                                                                                                                                   0.0s
 => CACHED [6/8] COPY img ./img                                                                                                                                         0.0s
 => ERROR [7/8] COPY build ./build                                                                                                                                      0.0s
------
 > [7/8] COPY build ./build:
------
Dockerfile:11
--------------------
   9 |     COPY public ./public
  10 |     COPY img ./img
  11 | >>> COPY build ./build
  12 |
  13 |     COPY docker/server ./server
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 5hveee2cyzvx4jizli87qwspa::xsdj7cxg4xv25jxaqpje3mh19: "/build": not found
Unable to find image 'vectara-answer:latest' locally
docker: Error response from daemon: failed to resolve reference "docker.io/library/vectara-answer:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed.
See 'docker run --help'.
Success! Application is running at http://localhost:80.\nTo shut it down use: docker container stop vanswer.

**Comment by cjcenizal** [comment]
@brianjking Here's a PR that fixes this issue: https://github.com/vectara/vectara-answer/pull/66. Feel free to check out the branch and confirm it fixes the bug for you.

For your issue with vectara-ingest, could you please [open an issue](https://github.com/vectara/vectara-ingest/issues/new) on that repo?

**Comment by brianjking** [comment]
@cjcenizal I pulled #66 down and still seem to be having issues

```
   ~/docu…ents/work/IgniteIQ/dev/answer     bug/options-drawer-lint ●  bash docker/run.sh config/brian default                                               (anaconda3)   06:06   18.09.23 

> vectara-answer@1.5.0 build
> react-scripts build


up to date, audited 1421 packages in 1s

245 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 moderate, 8 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  126.8 kB  build/static/js/main.70fe9410.js
  7.64 kB   build/static/css/main.b65fd42c.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

[+] Building 0.8s (13/13) FINISHED                                                                                                                                                 docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                               0.0s
 => => transferring dockerfile: 361B                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                                                                         0.6s
 => [1/8] FROM docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                                                   0.0s
 => => resolve docker.io/library/node:18@sha256:933bcfad91e9052a02bc29eb5aa29033e542afac4174f9524b79066d97b23c24                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                  0.1s
 => => transferring context: 3.60MB                                                                                                                                                                0.1s
 => CACHED [2/8] COPY docker/package.json ./                                                                                                                                                       0.0s
 => CACHED [3/8] RUN npm install                                                                                                                                                                   0.0s
 => CACHED [4/8] WORKDIR /usr/src/app                                                                                                                                                              0.0s
 => CACHED [5/8] COPY public ./public                                                                                                                                                              0.0s
 => CACHED [6/8] COPY img ./img                                                                                                                                                                    0.0s
 => CACHED [7/8] COPY build ./build                                                                                                                                                                0.0s
 => CACHED [8/8] COPY docker/server ./server                                                                                                                                                       0.0s
 => exporting to image                                                                                                                                                                             0.1s
 => => exporting layers                                                                                                                                                                            0.0s
 => => exporting manifest sha256:0612517c0986273d502d8ab57a2640b5cfdbea16bdcf2795553452cb3a4e2bf1                                                                                                  0.0s
 => => exporting config sha256:33cfa21919378da2c6dd2e3375d70e05d139a4055b9233a28f3d385a20eb5f97                                                                                                    0.0s
 => => exporting attestation manifest sha256:d3879f319c9fb772b84d65d5698cf7f679ef3672dc2c846822a86380fbbd542c                                                                                      0.0s
 => => exporting manifest list sha256:12e58c24e4db518cb445edfe19bdcd7fd07456ff380fc118a1c646088611e6d7                                                                                             0.0s
 => => naming to docker.io/library/vectara-answer:latest                                                                                                                                           0.0s
 => => unpacking to docker.io/library/vectara-answer:latest                                                                                                                                        0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Unable to find image 'vectara-answer:latest' locally
docker: Error response from daemon: failed to resolve reference "docker.io/library/vectara-answer:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed.
See 'docker run --help'.
Success! Application is running at http://localhost:80.\nTo shut it down use: docker container stop vanswer.
```

**Comment by brianjking** [comment]
Inside of Docker Desktop I can start the `vectara-answer` container manually and have attempted to run the commands after doing this too, no change.

<img width="951" alt="CleanShot 2023-09-18 at 06 45 02@2x" src="https://github.com/vectara/vectara-answer/assets/6786817/6f26b0de-ecea-4b0e-a6df-42f1165e25d0">

**Comment by cjcenizal** [comment]
@ofermend I see a couple errors here which seem related to Docker. In the se[cond-to-last comment](https://github.com/vectara/vectara-answer/issues/63#issuecomment-1723380234), the Docker process seems to report this error:

```
Unable to find image 'vectara-answer:latest' locally
docker: Error response from daemon: failed to resolve reference "docker.io/library/vectara-answer:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed.
```

Do you know what could be causing this?

In the last comment, the screenshot shows this log:

```
Proxy created: / -> https://undefined
```

I'm not sure what this means but it doesn't look right. Is this because `process.env.endpoint` is undefined here?

https://github.com/vectara/vectara-answer/blob/d9dcb3a8c0b097d764b51e7f2fbf3ef4aa07118d/docker/server/index.js#L11

**Comment by brianjking** [comment]
@ofermend @cjcenizal Did we mean to close this?

**Comment by cjcenizal** [comment]
Sorry, that was a mistake. Thanks for checking!

**Comment by brianjking** [comment]
@cjcenizal any idea what to do now? I'm in the Vectara discord and would love to hop on a call if you are open to it. :) Thanks!

**Comment by ofermend** [comment]
Was this fully resolved? @brianjking

**Comment by cjcenizal** [comment]
I'm going to close this for now but we will reopen if it turns out you're still running into this issue @brianjking.
