### ISSUE TITLE
Improve error message when queries.json isn't defined

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-answer#64]
If you try to run `bash docker/run.sh config/brian default` when `queries.json` isn't defined, you get this error message:

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Users/cj/Documents/Git/Vectara/vectara-answer/config/test/queries.json" to rootfs at "/usr/src/app/build/queries.json": mount /host_mnt/Users/cj/Documents/Git/Vectara/vectara-answer/config/test/queries.json:/usr/src/app/build/queries.json (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

Ideally, we should test for the presence of this file and throw a custom error message if it doesn't exist. The script should also exit so we don't attempt to open a tab at `localhost`.

**Comment by SaptarshiSarkar12** [comment]
@cjcenizal Can I work on this issue? This issue has been open for almost a year.

**Comment by cjcenizal** [comment]
@ofermend WDYT?

**Comment by ofermend** [comment]
SGTM. @SaptarshiSarkar12 - please validate first that this is still an issue.
