### ISSUE TITLE
Improve error message when Docker isn't running 

### ISSUE THREAD

**Issue by cjcenizal** [vectara/vectara-answer#65]
If you try to run `bash docker/run.sh config/brian default` when Docker isn't defined, you get this error message:

```
Error response from daemon: Bad response from Docker engine
docker: Error response from daemon: Bad response from Docker engine.
See 'docker run --help'.
```

Ideally, we should throw a custom error message if Docker isn't running. The script should also exit so we don't attempt to open a tab at `localhost`.

**Comment by SaptarshiSarkar12** [comment]
@cjcenizal Can I work on this issue?

**Comment by cjcenizal** [comment]
Thanks for volunteering @SaptarshiSarkar12 ! @ofermend WDYT?

**Comment by ofermend** [comment]
Yes, sounds good. Thanks!

**Comment by SaptarshiSarkar12** [comment]
@cjcenizal @ofermend Thank you. Can you please assign this issue to me? I will start working on it.
