### ISSUE TITLE
Queries.json Bug

### ISSUE THREAD

**Issue by hibaq86** [vectara/vectara-answer#85]
My queries.json questions will run locally but when I put my app in Azure, it only the default questions about AI. I have attached screenshots of what my questions are such as "What is rent subsidy".

I would like my questions to run on my Azure app.

 - OS: Sonoma 14.0
 - Browser: Chrome
 
![Screenshot 2023-10-05 at 6 32 19 PM](https://github.com/vectara/vectara-answer/assets/139479978/e7f691a4-3951-4e12-998c-f37ba6471972)

![Screenshot 2023-10-05 at 6 33 32 PM](https://github.com/vectara/vectara-answer/assets/139479978/d6bc0b78-8060-424b-ad05-ef41e687925e)

**Comment by ofermend** [comment]
This usually means queries.json is not handled properly with Azure. Was resolved by hosting on Render.
