### ISSUE TITLE
Enhance the docker/Dockerfile 

### ISSUE THREAD

**Issue by irfanazam1** [vectara/vectara-answer#92]
Currently, the Dockerfile depends upon the external commands like npm install, and npm run build to be able to include the build folder in the image. Instead, it should be a multi staged Dockerfile with build and package stage. The build stage builds the code and the package stage uses the artifacts. Idea  is that the Dockerfile should work on its own. This will make the build and push workflow smaller and easier to follow. Also, if someone wants to build locally from the Dockerfile, then it will work without any external dependencies.

**Comment by SaptarshiSarkar12** [comment]
@ofermend Can I work on this issue?

**Comment by ofermend** [comment]
for sure. would love to see your PR on this.

**Comment by SaptarshiSarkar12** [comment]
@ofermend Thank you 👍.
